################################################################################################
### Minimal configuration for shortest car distance only                                    ###
################################################################################################
ors:
  engine:
    # Configuration globale
    init_threads: 1
    graphs_data_access: RAM_STORE
    
    # Profil par défaut - désactivé
    profile_default:
      enabled: false
      build:
        source_file: /efs/osm/data_IK.osm.pbf
        elevation: false                    
        instructions: false                 
        optimize: false                     
        traffic: false                      
        preparation:
          methods:
            ch:
              weightings: shortest
              enabled: false                
            lm:
              weightings: shortest
              enabled: false                
            core:
              enabled: true                 
              weightings: shortest          
    
    # Profils spécifiques
    profiles:
      driving-car:
        graph_path: /efs/ors-run/graphs/
        enabled: true                       
        build:
          source_file: /efs/osm/data_IK.osm.pbf
          elevation: false                    
          instructions: false                 
          optimize: false                     
          traffic: false                      
          encoder_options:
            turn_costs: false               
            block_fords: false              
            use_acceleration: false         
            enable_custom_models: false     
          preparation:
            methods:
              ch:
                weightings: shortest
                enabled: false              
              lm:
                weightings: shortest
                enabled: false              
              core:
                enabled: true               
                threads: 2                  
                weightings: shortest        
          ext_storages:                     
            # WayCategory: {}               # Commenté = désactivé
            # HeavyVehicle: {}              # Commenté = désactivé
            # Tollways: {}                  # Commenté = désactivé
            # WaySurfaceType: {}            # Commenté = désactivé
            # RoadAccessRestrictions: {}    # Commenté = désactivé
        service:
          maximum_distance: 100000          
          maximum_waypoints: 10             
          maximum_visited_nodes: 500000     
          force_turn_costs: false           
          allow_custom_models: false        
          execution:
            methods:
              core:
                # Pas de landmarks actifs

  # Services endpoints
  endpoints:
    routing:
      enabled: true                         # ✅ Routing seulement
    matrix:
      enabled: false                        
    isochrones:
      enabled: false                        
    snap:
      enabled: false                        

# Configuration serveur minimale
server:
  port: 8082

# Logging minimal
logging:
  level:
    root: WARN                              # Réduire les logs
    org.heigit: INFO